### ISSUE TITLE
data processing

### ISSUE THREAD

**Issue by lisheng-han** [BarisYazici/deep-rl-grasping#10]
How to training ?
How do I output the reward curve after training ？

**Comment by BarisYazici** [comment]
Hi  @lisheng-han,

You can use the train script `python manipulation_main/training/train_stable_baselines.py train --config config/gripper_grasp.yaml --algo SAC --model_dir trained_models/SAC_full --timestep 100000 -v`
This script with the given arguments train with SAC algorithm and saves the model in trained_models folder 
with SAC_full name. It trains for 1m time-steps. -V flag spawns the visualizer GUI.

You can use the plot.py script under the scripts.
