### ISSUE TITLE
The results of your experiment are so wonderful

### ISSUE THREAD

**Issue by YKJK** [BarisYazici/deep-rl-grasping#23]
I have some Deep rl grasping models question, How to modify the program code?
1.Can the camera be changed to a fixed position?
2.I would like to know how to adapt this model for use in a real environment.
3.Is it possible to change the gripper to match the shape of the KUKA youBot gripper?
4.Could you provide instructions on changing the model of the grasped object?

**Comment by BarisYazici** [comment]
Sorry for replying with delay.

Camera position can be chaged. Try changing this https://github.com/BarisYazici/deep-rl-grasping/blob/fd2214e42a77e80fa986f04e27e043e0133b4d51/config/camera_transform.yaml#L1C1-L1C1

2. I haven't try in the real environment. But I guess you need to apply domain randomization during training. You can implement an interface for that sucht that the Pybullet simulation physics parameters are chaged. Contributions are welcomed :)
3. You can easily change the gripper or the robot look at other branches there should be examples of using the Franka and Kuka robot. In general you need to have a robot description file. https://github.com/BarisYazici/deep-rl-grasping/blob/fd2214e42a77e80fa986f04e27e043e0133b4d51/config/full_depth_obs.yaml#L3

4.  There is an example of using different object models in the repo -> https://github.com/BarisYazici/deep-rl-grasping/tree/fd2214e42a77e80fa986f04e27e043e0133b4d51/models/wooden_blocks. You need to have a similar structure. And change the config.yaml file to upload the models https://github.com/BarisYazici/deep-rl-grasping/blob/fd2214e42a77e80fa986f04e27e043e0133b4d51/config/full_depth_obs.yaml#L15C1-L15C25

**Comment by YKJK** [comment]
Thank you for your instant response. I will ask you again if I have any related questions!!
