### ISSUE TITLE
Grasping over single object spawn

### ISSUE THREAD

**Issue by SaiAakash** [BarisYazici/deep-rl-grasping#24]
Hi,

I was able to replicate the results of your work to a good extent. Did you try spawning a single object in the episode and make the gripper grasp that ? In such scenarios, the performance is very poor and the success rate doesn't go beyone 0.01. Do you have any idea why that happens ? Thanks in advance for your time.

**Comment by BarisYazici** [comment]
Can you post a screenshot of the scenario

**Comment by SaiAakash** [comment]
I have attached the screenshot. A single object spawned inside the tray for the Table Scene. 
![Screenshot from 2023-07-20 19-25-52](https://github.com/BarisYazici/deep-rl-grasping/assets/64794820/19d4430f-21d9-438d-8fa5-d9c5988c8616)

**Comment by BarisYazici** [comment]
Which model are you trying? Does it work when you try with the random object dataset?

**Comment by SaiAakash** [comment]
I am trying with some object models from the ycb dataset. The pre-trained models of this repository work well for this scenario (on both random objects and ycb dataset). The problem is this doesn't work well with training. During the training process for single object spawning, the success rate never goes past 0.01.

**Comment by BarisYazici** [comment]
I can understand that actually part of curriculum learning aim is to make the agent so easy to get reward to make it learn easier. If you have multiple objects in the scene it is easier for the agent to bump into one randomly and get a reward. Try to spawn multiple objects in the training but try testing with single object.
