### ISSUE TITLE
How to display the entire robotic arm

### ISSUE THREAD

**Issue by jkasdkjnasjkd** [BarisYazici/deep-rl-grasping#27]
How do you show the entire robotic arm, there is only one clip during the test?

**Comment by BarisYazici** [comment]
you can take a look at the kukaBranch. The urdf files are under models folder https://github.com/BarisYazici/deep-rl-grasping/tree/kukaExt/models/kuka_iiwa

**Comment by jkasdkjnasjkd** [comment]
Thank you very much for your answer, but the effect of migrating the training model of the fixture to the kuka manipulator is not too good, do you have any suggestions, or retrain it in the kuka manipulator

**Comment by BarisYazici** [comment]
It should similar to the given performance in my performance thesis. Maybe check if the robot’s reachability is good enough.

**Comment by jkasdkjnasjkd** [comment]
Thanks for your help!
