### ISSUE TITLE
A few questions about training

### ISSUE THREAD

**Issue by Sjey-Lyn** [BarisYazici/deep-rl-grasping#28]
Dear author.

Thank you for your awesome work, When I run the following command, I can't get good results.Would you like to suggest some possible reasons why this is?
python manipulation_main/training/train_stable_baselines.py train --config config/gripper_grasp.yaml --algo SAC --model_dir trained_models/SAC_full --timestep 100000 -v
and 
When I ran the other models provided, I didn't get good results either,like SAC_encoder_1mbuffer。

**Comment by BarisYazici** [comment]
Are you running in the simulation or on the real robot?

**Comment by Sjey-Lyn** [comment]
simulation @BarisYazici

**Comment by BarisYazici** [comment]
Is your gpu specs closer to the one used in the  project?

**Comment by BarisYazici** [comment]
Just to compare one to one.
Could you just try the inference in the beginning? Can you try with the trained model SAC 1m depth buffer?

**Comment by Sjey-Lyn** [comment]
I tried again and found it worked.I may have made some mistakes earlier.

**Comment by BarisYazici** [comment]
Perfect! Good luck with your research :)

**Comment by Sjey-Lyn** [comment]
When I finish the training and lambda is 0.125, does it mean that the course is not over and the model is still able to improve?
