### ISSUE TITLE
PPO algo performs badly

### ISSUE THREAD

**Issue by HarrisonC7** [BarisYazici/deep-rl-grasping#29]
The PPO algorithm is difficult to converge，and the gripper always move up and away from the table.Could you please give me some hint about it.Sincerely appreciate it!

**Comment by BarisYazici** [comment]
I would recommend using SAC. It performed the best.

**Comment by HarrisonC7** [comment]
> I would recommend using SAC. It performed the best.

Thanks,SAC indeed did a wonderful job!
