### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by jamesking23** [BarisYazici/deep-rl-grasping#5]
When I run this environment,I couldn't see the log.csv,so I use the tensorboard,but the success rate is different from the terminal?Could you help me?

**Comment by jamesking23** [comment]
Monitor only saves reward,but how to save the success rate?

**Comment by BarisYazici** [comment]
Yes, for this you need to edit the stable-baselines monitor.py file as in [here](https://github.com/BarisYazici/bdq_sb/blob/plotmonitor/stable_baselines/bench/monitor.py). 

1.  Fork the stable-baselines [repo](https://github.com/hill-a/stable-baselines) and put the folder under your deep-rl-grasping. 
2. Then change the [monitor.py ](https://github.com/hill-a/stable-baselines/blob/14ee347a7cc9535cc23b6bc8e7693209b19fd7f6/stable_baselines/bench/monitor.py) as in [here](https://github.com/BarisYazici/bdq_sb/blob/plotmonitor/stable_baselines/bench/monitor.py).
3. After this change don't forget to install the new version of stable-baselines.  
First do `cd stable-baselines` then do `pip install -e .`  If you don't do that you will still have the old version of stable baselines.

**Comment by jamesking23** [comment]
Thanks for your help!
