### ISSUE TITLE
In real robot, do you calibrate the extrinsic parameter? 

### ISSUE THREAD

**Issue by nizhihao** [BarisYazici/deep-rl-grasping#7]
Hello, Thanks for your share.
I have a question in real robot, do you calibrate the extrinsic parameter?  and could you give me some ideas to run you code in real robots. 
Thanks very much!

**Comment by BarisYazici** [comment]
Hey Neo! I didn't test on a hardware robot. But I am interested in your result. Let me know when you get some tests done.
