### ISSUE TITLE
Train encoder

### ISSUE THREAD

**Issue by SHZ2006** [BarisYazici/deep-rl-grasping#8]
Hello! 
Could you help me to train my custom encoder for different image sizes (I mean for real images)?
Which file I have to run exactly and also If you can provide example dataset for that.

**Comment by BarisYazici** [comment]
You can create your own dataset, with collect_dataset.py [script](https://github.com/BarisYazici/deep-rl-grasping/blob/master/scripts/collect_dataset.py). To change the image size, you need to change the height and width here in this [file](https://github.com/BarisYazici/deep-rl-grasping/blob/master/config/camera_info.yaml). To train the encoder, run this [script](https://github.com/BarisYazici/deep-rl-grasping/blob/master/manipulation_main/training/train_encoder.py).

**Comment by SHZ2006** [comment]
Thank you Baris, I am wondering if you write a sample command for dataset creation and training. I confused how to indicate config files and other options for that like model_dir and so on.
Best,

**Comment by BarisYazici** [comment]
Create a dataset of depth images with the given command below.

` python scripts/collect_dataset.py --config config/gripper_grasp.yaml --data_path data_sample.pkl`

Then change the data_path in **encoder.yaml** [file](https://github.com/BarisYazici/deep-rl-grasping/blob/master/config/encoder.yaml#L11) to point out the **data_sample.pkl** in your working directory.

After doing that run the below command:

`python manipulation_main/training/train_encoder.py encoder_sample train --config config/encoder.yaml
`

**Comment by SHZ2006** [comment]
Thanks a lot. Is it possible to train the encoder on real images?

**Comment by BarisYazici** [comment]
Yes, sure it should be possible.
